# =============================================================================
# Cloud Build Configuration for AI Teaching Agent Team
# Deploys to Google Cloud Run
# =============================================================================
#
# Prerequisites:
# 1. Enable Cloud Build API: gcloud services enable cloudbuild.googleapis.com
# 2. Enable Cloud Run API: gcloud services enable run.googleapis.com
# 3. Enable Artifact Registry: gcloud services enable artifactregistry.googleapis.com
# 4. Grant Cloud Build service account Cloud Run Admin & Service Account User roles
#
# Usage:
# - Manual trigger: gcloud builds submit --config cloudbuild.yaml
# - Auto trigger: Connect repo via Cloud Build triggers
# =============================================================================

substitutions:
  _SERVICE_NAME: ai-teaching-agent-team
  _REGION: us-central1
  _ARTIFACT_REGISTRY: docker.pkg.dev/${PROJECT_ID}/cloud-run-images

steps:
  # ---------------------------------------------------------------------------
  # Step 1: Build Docker image with caching
  # ---------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --cache-from ${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:latest \
          -t ${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:${SHORT_SHA} \
          -t ${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:latest \
          .

  # ---------------------------------------------------------------------------
  # Step 2: Push to Artifact Registry
  # ---------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - '--all-tags'
      - '${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}'
    waitFor:
      - 'build'

  # ---------------------------------------------------------------------------
  # Step 3: Deploy to Cloud Run
  # ---------------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'STREAMLIT_SERVER_PORT=8080,STREAMLIT_SERVER_ADDRESS=0.0.0.0'
    waitFor:
      - 'push'

# Store images in Artifact Registry
images:
  - '${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:${SHORT_SHA}'
  - '${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Build timeout (20 minutes)
timeout: '1200s'
